11 receive data from matlab
Baby-Monitor-Simulator/S6BabyMonitor pull request #13
Opened 2023-03-02 14:14 UTC by dainank

2023-03-02 14:23 UTC, dainank commented
Duplicate of #11

2023-03-20 13:05 UTC, WinteryFox requested changes

2023-03-20 13:05 UTC, WinteryFox commented on src/main/kotlin/MatlabConnection.kt
> +    fun RunModel(model: MatlabModel){
Function names should follow camelCase, not UpperCamelCase. Remember to make full use of IntelliJ's auto-formatting feature (ctrl + alt + L on Windows), since there's some general inconsistencies that will be taken care of by simply doing so.

2023-03-20 13:05 UTC, WinteryFox commented on src/main/kotlin/MatlabConnection.kt
> +    }
Single line functions can be rewritten like;
```kotlin
fun getSingleVar(varName: MatlabSingleVariable) = engine.getVariable(varName.type)
```
Notice also how you do not need to explicitly define the type, the return type is inferred from the right-hand value.

2023-03-20 13:10 UTC, dainank commented on .gitignore
> +!lib/engine.jar
`!lib/*` might be better here since we will always want to permit all local dependencies in this `lib` folder.

2023-03-20 13:10 UTC, dainank commented on src/main/kotlin/Main.kt
> +    //first run the model
consider removing all these comments, the lines in code explain it for themselves

2023-03-20 13:10 UTC, dainank commented on README.md
> +- Select all projects
I think keep first sentence but yeah replace the rest, stating that MATLAB needs to be installed locally for this program to run.

2023-03-20 16:10 UTC, WinteryFox requested changes

2023-03-22 05:42 UTC, jonyray commented on README.md
> +- Select all projects
yes u are right, im trying another way

2023-03-23 09:15 UTC, merged